---
title: "ANALYSE ATS"
format: 
  html:  
    page-layout: custom
    css: styles.css
    self-contained: false
---



```{r}
#| echo: false
#| warning: false
#| message: false
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
source("graphics/plotly.R")
source("opportunite.R")
output<-""
```

```{r}
procedure<-function(periode){
p<-generer_graphique(actif,periode)
if(!is.null(p)){analyse_opportunite(periode = periode,type=type)}
return(p)
}
```

```{r}
print(Sys.time())
```

# DEVISES
```{r}
type="F"
```

:::::::::::::::::::::::::::::::::::::::::::::::::::: panel-tabset
## EURUSD

```{r}
actif="EURUSD=X"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```

:::::::::


## USDJPY

```{r}
type="JPY"
actif="USDJPY=X"
```
::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::

```{r, results='asis' }
cat(output)
output<-""
```

:::::::::




## GBPUSD

```{r}
type="F"
actif="GBPUSD=X"
```
::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::


## AUDUSD

```{r}
actif="AUDUSD=X"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::

```{r, results='asis' }
cat(output)
output<-""
```
:::::::::





## USDCAD

```{r}
actif="USDCAD=X"
```
::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::

## USDCNY

```{r}
type="JPY"
actif="USDCNY=X"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::


## USDCHF

```{r}
type="F"
actif="USDCHF=X"
```
::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::

```{r, results='asis' }
cat(output)
output<-""
```
:::::::::

## EURGBP

```{r}
actif="EURGBP=X"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::::



# INDICES
```{r}
type="I"
```

::::::::::::::::::::::::::::::: panel-tabset
## CAC

```{r}
actif="^FCHI"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::



## DJ

```{r}
actif="^DJI"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::


## NASDAQ

```{r}
actif="^IXIC"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::


## DAX

```{r}
actif="^GDAXI"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::


## S&P 500

```{r}
actif="^GSPC"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::


## IBEX

```{r}
actif="^IBEX"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::

:::::::::::::::::::::::::::::::


# COMO

::: panel-tabset
## GOLD
```{r}
type="A"
```



```{r}
actif="GC=F"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::


## SILVER

```{r}
actif="SI=F"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::


## COPPER

```{r}
actif="CC=F"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::



## OIL

```{r}
actif="CL=F"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::


::: 


# ACTIONS

::::::::::::::::::::::::::::::: panel-tabset
## NOVA

```{r}
actif="ALNOV.PA"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::



## ODET

```{r}
actif="ODET.PA"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::


## THERANEXUS

```{r}
actif="ALTHX.PA"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::





## COFACE

```{r}
actif="COFA.PA"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::

## LYXOR ETF

```{r}
actif="PUST.PA"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::



## CREDIT AGRICOLE

```{r}
actif="ACA.PA"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::


## AIR LIQUIDE

```{r}
actif="AI.PA"
```

::::::::: {layout="[[1,1,1],[2,2,2]]"}
::: {#row-1 .g-col-4}
```{r}
periode="daily"
procedure(periode)
```
:::

::: g-col-4
```{r}

periode="weekly"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="monthly"
procedure(periode)

```
:::

::: {#row-2 .g-col-4}
```{r}

periode="annual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="semiannual"
procedure(periode)
```
:::

::: g-col-4
```{r}
periode="quarterly"
procedure(periode)   
```
:::
```{r, results='asis' }
cat(output)
output<-""
```
:::::::::


::::::::::::::::::::::::::::::: 




