name: Deploy Quarto Site to Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  render-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Installer les dépendances système nécessaires
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up R dependancies
        uses: r-lib/actions/setup-r-dependencies@v2  
      
      - name: Cache R packages
        uses: actions/cache@v4
          with:
            path: ${{ env.R_LIBS_USER }}
            key: ${{ runner.os }}-r-${{ hashFiles('DESCRIPTION') }}
              restore-keys: |
                ${{ runner.os }}-r-
  
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        run: |
          quarto render --output-dir docs/_site
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # Étape cruciale
        with:
          path: docs/_site
          name: gh-pages
          
    

  deploy:
    runs-on: ubuntu-latest
    needs: render-deploy
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Pas de paramètre "path" ici
        with:
          artifact_name: gh-pages