name: Update Stock Data
env:
  TOKEN_GIT: ${{ secrets.TOKEN_GIT }}

on:
  schedule:
    - cron: '0 1,4,7,10,13,16,19,22 * * 0-4'  # UTC : 00h, 03h..., 21h tous les jours
  workflow_dispatch:  # permet aussi un déclenchement manuel

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run stock data script
      run: python intraday/recup.py

    - name: Upload csv artifact
      uses: actions/upload-artifact@v4
      with:
        name: stock-data-csv
        path: donnees.csv
